config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :import_files do
      resources :import_rows
      member do
        get :generate
      end
    end
    get '/', to: redirect('/admin/goals')
    resources :goals do
      resources :interactions
    end
    resources :interactions do
     resources :contents
    end

    resources :contents
    resources :import_rows
  end
  
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  namespace :api do
    resources :bootstrap, only: [:index]

    resources :goals do
      member do
        delete :purge
      end
      resources :interactions do
        member do
          get :check_answer
          post :submit_review
        end
      end
      resources :import_files do
        member do
          post :generate
        end
      end
    end

    # Interactions are only accessible through goals and content through interactions.
    resources :interactions, only: [] do
      resources :contents
    end

    resources :import_files do
      resources :import_rows
    end
  end
end

app/models/content.rb
  class Content < ApplicationRecord
  include Fae::BaseModelConcern

  PROMPT = 'Prompt'
  CRITERION = 'Criterion'

  TYPES = [PROMPT, CRITERION]

  def fae_display_field
    title
  end
  
  has_fae_image :stimulus

  belongs_to :interaction, required: true

  default_scope { order(:title) }

  validates_presence_of :title
  validates_inclusion_of :content_type, in: TYPES

  validates_presence_of :stimulus, unless: :copy?
end

app/controllers/admin/contents_controller.rb
module Admin
  class ContentsController < Fae::BaseController
    before_action :set_interaction

    def index
      # :interaction set by AdminBaseController for index routes generated by fae after restful action
      if @interaction
        @items = Content.where(interaction_id: @interaction.id)
      else
        @items = Content.all
      end
    end

    private

    def build_assets
      @item.build_stimulus if @item.stimulus.blank?
    end

    def set_interaction
      cookies[:interaction_id] = params[:interaction_id] if params[:interaction_id]
      @interaction = Interaction.find_by_id(cookies[:interaction_id])
    end

  end
end

app/controllers/api/contents_controller.rb
module Api
  class ContentsController < ApplicationController
    before_action :set_interaction

    # GET /interactions/:interaction_id/contents
    def index
      json_response(@interaction.contents)
    end

    # GET /interactions/:interaction_id/contents/:id
    def show
      set_interaction_content
      return json_response("Couldn't find Content", :not_found) unless @content
      json_response(@content, status)
    end

    # POST /interactions/:interaction_id/contents
    def create
      @content = @interaction.contents.create!(content_params)
      return json_response("Couldn't find Content", :not_found) unless @content
      json_response(@content, :created)
    end

    # PUT /interactions/:interaction_id/contents/:id
    def update
      set_interaction_content
      return json_response("Couldn't find Content", :not_found) unless @content
      @content.update(content_params)
      head :no_content
    end

    # DELETE /interactions/:interation_id/contents/:id
    def destroy
      set_interaction_content
      return json_response("Couldn't find Content", :not_found) unless @content
      @content.destroy
      head :no_content
    end

    private

    def content_params
      params.permit(:title, :content_type, :description, :copy, :score, :descriptor)
    end

    def set_interaction
      @interaction = Interaction.preload(:contents).find(params[:interaction_id])
    end

    def set_interaction_content
      @content = @interaction.contents.find { |c| c.id == params[:id].to_i} if @interaction
    end
  end
end

app/views/admin/contents/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    - if @interaction
      = f.input :interactions, as: :hidden,
              input_html: {name: "content[interaction_id]", value: @interaction.id, "data-klass" => "Content"}
      label
        .control-label Interaction
      h3 = @interaction.title
        |
    - else
      = fae_association f, :interactions

    = fae_input f, :title
    = fae_pulldown f, :content_type, collection: Content::TYPES
    = fae_input f, :description
    = fae_input f, :copy
    = fae_input f, :score
    = fae_input f, :descriptor


    = fae_image_form f, :stimulus

app/views/admin/contents/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  - if @interaction
    h3 = link_to "Interaction: #{@interaction.title}", admin_goal_interactions_path(goal_id: @interaction.goal_id)
    
  table.js-sort-column
    thead
      tr
        - unless @interaction
          th width="20%" Interaction
        th Title
        th width="10%" Type
        th Description
        th Copy
        th Image
        th Descriptor
        th Score
        th.-action data-sorter="false"
        th.-action-wide Modified
    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            - unless @interaction
              td = item.interaction.title
            td = link_to item.fae_display_field, edit_admin_content_path(item)
            td = item.content_type
            td = item.description
            td = item.copy
            - if item.stimulus.nil? || item.stimulus.asset.url.nil?
              td = ' - '
            - else
              td = image_tag(item.stimulus.asset.url, size: "50")
            td = item.descriptor
            td = item.score
            td = fae_delete_button item
            td = fae_date_format item.updated_at
      - else
        tr: td colspan="#{(@interaction)?8:9}" No items found