config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :import_files do
      resources :import_rows
      member do
        get :generate
      end
    end
    get '/', to: redirect('/admin/goals')
    resources :goals do
      resources :interactions
    end
    resources :interactions do
     resources :contents
    end

    resources :contents
    resources :import_rows
  end
  
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  namespace :api do
    resources :bootstrap, only: [:index]

    resources :goals do
      member do
        delete :purge
      end
      resources :interactions do
        member do
          get :check_answer
          post :submit_review
        end
      end
      resources :import_files do
        member do
          post :generate
        end
      end
    end

    # Interactions are only accessible through goals and content through interactions.
    resources :interactions, only: [] do
      resources :contents
    end

    resources :import_files do
      resources :import_rows
    end
  end
end

app/models/import_row.rb
class ImportRow < ApplicationRecord
  include Fae::BaseModelConcern
  include ActiveModel::Validations

  validates_uniqueness_of :title, scope: :import_file_id
  validates_with ImportRowValidator

  def fae_display_field
    title
  end

  # order by id for ease of review in sequential import
  default_scope { order('id') }

  belongs_to :import_file, required: true
  has_one :interaction

  def json
    @json ||= JSON.parse(json_data)
  end
end

app/controllers/admin/import_rows_controller.rb
module Admin
  class ImportRowsController < Fae::BaseController
    before_action :set_import_file

    def index
      if @import_file
        @items = ImportRow.where(import_file_id: @import_file.id)
      else
        @items = ImportRow.all
      end
    end

    def set_import_file
      cookies[:import_file_id] = params[:import_file_id] if params[:import_file_id]
      @import_file = ImportFile.find_by_id(cookies[:import_file_id])
    end

  end
end

app/controllers/api/import_rows_controller.rb
module Api
  class ImportRowsController < ApplicationController
    before_action :set_import_file

    # GET /import_file/:import_file_id/import_rows
    def index
      json_response(@import_file.import_rows)
    end

    # GET /import_file/:import_file_id/import_rows/:id
    def show
      json_data_response(:ok)
    end

    # POST /import_file/:import_file_id/import_rows
    def create
      @import_row = @import_file.import_rows.create!(import_row_params)
      json_data_response(:created)
    end

    # PUT /import_file/:import_file_id/import_rows/:id
    def update
      @import_row.update(import_row_params)
      head :no_content
    end

    # DELETE /import_file/:import_file_id/import_rows/:id
    def destroy
      @import_row.destroy
      head :no_content
    end

    #
    private

    def import_row_params
      params.permit(:title, :json_data)
    end

    def set_import_file
      # require the goal context for all import_row requests
      return unless params[:import_file_id]
      @import_file = ImportFile.preload(:import_rows).find(params[:import_file_id])
      @import_row = ImportRow.find(params[:id]) if params[:id]
    end

    # json_data contains the csv_file rows. It's stored as a string.
    # Convert the string to Json
    def json_data_response( status)
      response =
          {
              "id": @import_row.id,
              "title": @import_row.title,
              "import_file_id": @import_row.import_file_id,
              "created_at": @import_row.created_at,
              "updated_at": @import_row.updated_at,
              "json_data": JSON.parse(@import_row.json_data),
          }
      json_response(response, status)
    end
  end
end

app/views/admin/import_rows/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :title
    = fae_input f, :json_data

    = fae_association f, :import_file

app/views/admin/import_rows/edit.html.slim
== render 'form'

app/views/admin/import_rows/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Title
        th.-action data-sorter="false"
        th.-action-wide Modified

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_import_row_path(item)
            td = fae_delete_button item
            td = fae_date_format item.updated_at
      - else
        tr: td colspan="3" No items found

app/views/admin/import_rows/new.html.slim
== render 'form'